### Create a new user
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make"  : "Toyota",
  "model" : "Corolla",
  "year"  : 2020,
  "price" : 20000,
  "mileage": 15000,
  "lng" : -122.4194,
  "lat" : 37.7749,
}