### Create a new user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "laith@laith123.com",
  "password": "ex1dqwdqw3131amplePassqwdqwdqwdword"
}
### Sign in a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "laith@laith123.com",
  "password": "ex1dqwdqw3131amplePassqwdqwdqwdword"
}

### WHO AM I
GET http://localhost:3000/auth/whoami


### Sign out a user
POST http://localhost:3000/auth/signout
Content-Type: application/json

{
  "email": "laith@laith.com",
  "password": "ex1dqwdqw3131amplePassqwdqwdqwdword"
}


### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users
GET http://localhost:3000/auth

### delete a user with a given ID
DELETE http://localhost:3000/auth/5

### Update a user with a given ID
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "a@a.a"
}

